# default: &default
#   adapter: postgresql
#   encoding: unicode
#   username: username
#   password: password
#   host: localhost
#   port: 5432
#
# development:
#   <<: *default
#   database: messageapp_development
#
# test:
#   <<: *default
#   database: messageapp_test
